### PR TITLE
Added Status Feature in Jobprofile #9

### LINKED ISSUE #9: Status Feature in Jobprofile
### New Column Status particular for every user with values -
1. Apply
2. Applied

Currently the same functionality is implemented in yourapp which can be accessed by clicking "Click here to see your applied Applications" on show company page.

Thanks for showing interest in our project

### PR DESCRIPTION
**Pull request by codesankalp**
Added an column in job profile page to show the status of the
application of the user.

Fixes #9

### CODE REVIEW

**Comment by codesankalp** [comment]
@prakharepo please review this pull request.

**Review by prakharepo — APPROVED** [review]

**Comment by codesankalp** [comment]
@prakharepo if you have more issues then just open that issue and tag me if you want me to solve that issue.
Thanks :relaxed:

**Comment by codesankalp** [comment]
https://hacktoberfest.digitalocean.com/hacktoberfest-update
@prakharepo please read this make the changes as my pull request have been merged you have to add labels also.
Thanks.

**Comment by prakharepo** [comment]
Hey @codesankalp thanks for this information, i have made required changes.

**Comment by codesankalp** [comment]
Thanks @prakharepo

**Pull request merged**
